export default [
  { label: "أي مكان", value: null },
  { label: "المنزل", value: "home" },
  { label: "المدرسة", value: "school" },
  { label: "الجبل", value: "mountain" },
  { label: "الحديقة", value: "garden" },
  { label: "المستشفى", value: "hospital" },
  { label: "الفضاء", value: "space" },
  { label: "المطعم", value: "restaurant" },
  { label: "المكتبة", value: "library" },
  { label: "البحر", value: "sea" },
  { label: "المسرح", value: "theater" },
  { label: "الملعب", value: "playground" },
  { label: "المتحف", value: "museum" },
  { label: "الجزيرة", value: "island" },
  { label: "المول", value: "mall" },
  { label: "المطار", value: "airport" },
  { label: "المحطة", value: "station" },
  { label: "المخبز", value: "bakery" },
  { label: "المملكة", value: "kingdom" },
  { label: "المزرعة", value: "farm" },
  { label: "المصنع", value: "factory" },
  { label: "المكتب", value: "office" },
  { label: "المخبز", value: "bakery" },
];
